### ISSUE TITLE
Ability to inject attributes?

### ISSUE THREAD

**Issue by chipsenkbeil** [TedDriggs/darling#111]
Given that darling is one of the nicer ways to play with attributes, I was wondering if anyone had used it to inject new attributes when writing a proc macro attribute.

I'm doing this manually today in https://github.com/chipsenkbeil/entity-rs/blob/main/entity_macros/src/attribute.rs for a couple of scenarios:

1. Detect if a derive of one of my macros is missing and insert it. I also do this for **Clone** and **serde::Serialize/Deserialize**, but those can be opted out.
2. Inject fields with associated attributes if missing like `#[ent(id)] id: Id`

The process of injecting is a bit painful as I have to search for the attribute and either add it to a nested meta list or create the parent attribute itself. E.g. I create `derive(Ent)` or I inject `Ent` into `derive(Clone, PartialEq, Eq)` to become `derive(Clone, PartialEq, Eq, Ent)`.

I'm injecting because I don't want to recreate the entire struct (or enum) I'm modifying. Rather, I want to fill in the missing gaps. Maybe this is done in a better way by others. My main challenges were writing custom parsers so I could create new attribute nested meta and determine if the attribute already existed.

**Comment by chipsenkbeil** [comment]
Another question related to the derive detection. If I wanted to use darling to capture this, my first thought would be to do something like:

```rust
#[derive(FromDeriveInput)]
#[darling(attributes(derive, ent), supports(struct_named))]
pub struct Ent {
    pub ident: Ident,
    pub vis: Visibility,
    pub generics: Generics,
    pub data: ast::Data<(), EntField>,
    #[darling(default)]
    pub derive_attr: Option<DeriveAttr>,
}

#[derive(FromMeta)]
struct DeriveAttr {
    #[darling(default, rename = "Clone")]
    has_clone: bool,
    #[darling(default, rename = "Ent")]
    has_ent: bool,
    #[darling(default, rename = "Serialize")]
    has_serde_serialize: bool,
    #[darling(default, rename = "Deserialize")]
    has_serde_deserialize: bool,
}
```

The challenge is that the above wouldn't work for a derive with types like `serde::Serialize` instead of `Serialize`. I haven't tried darling's map function, so maybe I could use that to check for the type itself? Ideally, I'd want a flag that says "check if the end of the path is Serialize," which is what I do by hand right now. Does darling already support this? Or is this something I should continue doing myself?

**Comment by TedDriggs** [comment]
I've not seen any other proc-macro crates attempt this, likely because adding `derive` to the type your macro receives modifies the deriving type's public API in ways beyond what's implied by the `derive` contract. Given that Rust normally errs on the side of being explicit, I would personally rather get an error that `Clone` is not implemented than have it silently add one that I don't notice.

Similarly, I'd personally prefer an error for missing fields rather than the size and layout of my struct being modified by the macro. Down the road, it would be really interesting if Rust allowed diagnostics to carry enough data for a tool such as `rust-analyzer` to suggest a fix for macro-created diagnostics, and if that happens `darling` will seek to add support for auto-fixes of errors such as missing name-value pairs in attributes.

**Comment by chipsenkbeil** [comment]
> I've not seen any other proc-macro crates attempt this, likely because adding `derive` to the type your macro receives modifies the deriving type's public API in ways beyond what's implied by the `derive` contract. Given that Rust normally errs on the side of being explicit, I would personally rather get an error that `Clone` is not implemented than have it silently add one that I don't notice.
> 
> Similarly, I'd personally prefer an error for missing fields rather than the size and layout of my struct being modified by the macro. Down the road, it would be really interesting if Rust allowed diagnostics to carry enough data for a tool such as `rust-analyzer` to suggest a fix for macro-created diagnostics, and if that happens `darling` will seek to add support for auto-fixes of errors such as missing name-value pairs in attributes.

I will say that modifications are becoming more common and is a trait of producing a proc macro attribute rather than a proc macro derive. Examples like async-graphql come to mind, so I wouldn't discount that.

**Comment by TedDriggs** [comment]
> I haven't tried darling's map function, so maybe I could use that to check for the type itself? Ideally, I'd want a flag that says "check if the end of the path is Serialize,"

That _should_ work. You'd have a function that took a `darling::util::PathList` in and then returned a `DeriveAttrs`. What I'm not sure of offhand is how well that would deal with multiple `derive` attributes; you might need to do a `Vec<PathList>` in conjunction with `#[darling(multiple)]`, and then combine those in your mapping function.

> Examples like async-graphql come to mind

Are you referring to [this behavior on custom scalars](https://async-graphql.github.io/async-graphql/en/custom_scalars.html)? Their documentation otherwise didn't mention source modifications that I could find. That said, my job has pulled me away from Rust (and coding in general), so I am a bit behind the state of the art in proc-macro authoring.

The goal of `darling` is to make `serde`-caliber proc-macros as easy to write and as polished to use as `serde` makes serialization and deserialization. While I'm not yet sure how I feel about doing work specifically to streamline this particular kind of injection, I'm open to making larger changes to the library to support the new use-cases that new proc-macro features enable.
