### ISSUE TITLE
Investigate GitHub actions for CI

### ISSUE THREAD

**Issue by TedDriggs** [TedDriggs/darling#117]
Travis-CI is now taking upwards of 40 minutes to _start_ the CI job, which is not conducive to continuous testing.

**Comment by chipsenkbeil** [comment]
I just went through this in case you want a reference for Github actions: https://github.com/chipsenkbeil/entity-rs/blob/main/.github/workflows/ci.yml

I test the default features, all features, and no default features. Because of the way dependencies are pulled in during all features, I had to limit it to just the entity crate instead of all crates. For no default features, you can't use the workspace option to select everything and instead have to specify a manifest, but I don't think either of these warts would apply to darling.

**Comment by TedDriggs** [comment]
@chipsenkbeil thanks for the guidance! Yours was a great starting point, and the speed improvement over Travis is frankly stunning.

**Comment by chipsenkbeil** [comment]
@TedDriggs, I just discovered that my CI was missing an `override: true` in the test section. You'll need that to get it to use the proper toolchain, which is why my nightly run wasn't detected by rustversion.

![Screen Shot 2021-01-06 at 10 52 14 AM](https://user-images.githubusercontent.com/2481802/103796785-4194cd80-500d-11eb-9e71-6d11f0647f5a.png)
