### ISSUE TITLE
Mechanism to do interstitial parsing of a field via `FromMeta`.

### ISSUE THREAD

**Issue by tobz** [TedDriggs/darling#182]
I'm currently working on an issue where I want to parse both integers and floats when presented as the value to a path (`#[foo(attr(val = 1000))]` or `#[foo(attr(val = 1000.0))]`) as for my purposes, they are semantically identical.

I've trawled through a lot of the related issues where you've mentioned the idea of doing partial parsing, to get the field down to `syn::Lit` or `syn::Meta` or, in my case, `Result<u64, syn::Meta>` and then handle the two different cases.. but I personally find this a bit unergonomic/inelegant as it requires me to have to expose weird accessor methods, or conversion methods, to get to my final desired state of having a single data type: `f64`, in this case.

Is there any available path towards a design that allowed instructing the codegen to use an entirely different `T` for the field before passing that value to a method that would do the `T` -> `U` conversion, where `U` was the actual field type?

It feels like this could possibly exist as a new helper attribute, a spiritual cousin to `serde`'s `deserialize_with`, that takes a method to use to do the parsing... like `map` or `and_then`, but with another type argument to allow driving the type to parse with initially, and the type the method will give back matching the field.

**Comment by TedDriggs** [comment]
I believe what you're looking for is `#[darling(with = "...")]`, which takes a path to a function whose signature is `(mi: &Meta) -> darling::Result<T>`.

```rust
#[derive(FromMeta)]
struct Demo {
    #[darling(with = "float_or_int")]
    value: f64
}

fn float_or_int(meta: &Meta) -> darling::Result<f64> {
}
```

---

On this particular use-case, the idea of `darling` transparently handling ints as floats was discussed [here](https://github.com/TedDriggs/darling/issues/176#issuecomment-1095547888); I ultimately felt it was unwise since Rust doesn't allow bare numbers to be considered float literals without a type suffix in normal code, and deviating from that for attributes felt iffy.

**Comment by tobz** [comment]
Yeah, I can see the case for making the stdlib float impls not play fast and loose with accepting either int or float literals.. since you eventually have to make a decision about handling loss of precision past the mantissa range, etc etc...

I did, however, totally miss the `with` attribute.  I'll give that a shot.  Appreciate the fast response. 👍🏻
