### ISSUE TITLE
Possible to group multiple flag fields as one-but-not-multiple?

### ISSUE THREAD

**Issue by tobz** [TedDriggs/darling#188]
I'm working on some code where I want to parse a bunch of arbitrary paths given to an attribute macro. Most of the paths I want to accept are true standalone flags. Some of them, however, or meant to be exclusive on some other particular flags. This is to say, that I might allow you do specify `foo`, `bar`, or `quux` for `#[my_attr(the_path)]` but you shouldn't be able to do `#[my_attr(foo, bar)]`.

I realize that this is an already solved problem if I simply used, say, an enum with corresponding variants and then did `#[my_attr(thing = "foo")]`... but I'm trying to see if I can do this with a flag-esque approach... because there's a lot of pre-existing code of mine using the flag-esque approach and now I'm genuinely curious if there's a way. :P

**Comment by TedDriggs** [comment]
It's doable, but you have to write the collision checking rules yourself: `#[darling(and_then="...")]` provides a good place to hook in your conflict detection logic.

There's a real-world example of this [here](https://github.com/colin-kiegel/rust-derive-builder/blob/master/derive_builder_core/src/macro_options/darling_opts.rs#L50-L70) in `derive_builder`, where someone can pass `#[builder(public)]` or `#[builder(private)]`, and passing both wouldn't be very sensible.

If you're _really_ detail-oriented, you'll notice that there's one slightly annoying effect of this solution: This conflict check will only run if all other checks passed. Normally, `darling` is really good about continuing to work so that it gathers all the errors up for your crate's user in one go. It's much nicer than being given only one error at a time by the compiler. 

Unfortunately, in this case, some errors may have left the derived impl in a spot where it can't build the struct, and therefore it can't create a value to pass into the `and_then="..."` function. That means users will get two waves of errors:

1. Errors that block construction of the receiver struct
2. "Business logic" validation errors that run on the completed struct.

To mitigate how annoying this might be, I recommend using `and_then` at only the topmost layer of your receiver objects, and then manually descending into child structs to check for errors. That way, a case 2 failure in a child field won't become a case 1 failure for the parent, prolonging the user's back-and-forth with the compiler as they try to get everything in order.

**Comment by tobz** [comment]
Yeah, that all makes sense and I appreciate the thought in the response. It's obviously a contrived example that really stretches the nature of free-form attribute input and structured parsing, so I sort of figured that when I didn't find any issues around it, or example code, or obvious way to do so... that I was probably not going to find a magical solution. :)

Thanks again for the gut check. 👍🏻
