### ISSUE TITLE
Support associated types as type params

### ISSUE THREAD

**Issue by lu-zero** [TedDriggs/darling#190]
given a struct
```
struct S {
  f: F<S::Associated>
}
```

Would be great if in addition to `collect_type_params` a `collect_type_params_path` could return `S::Associated`.

**Comment by TedDriggs** [comment]
Are those part of syn::Generics? I don’t think they are.

**Comment by lu-zero** [comment]
The example was wrong
```
trait Trait { 
    type Associated;
}

struct A<S: Trait> {
  f: F<S::Associated>
}
```

Sorry.

**Comment by TedDriggs** [comment]
Does `collect_type_params` currently miss the use of `S` here? If you can provide a more complete example of the inputs and outputs you're looking for, that would be helpful.

**Comment by lu-zero** [comment]
It does not miss it but I would need to find either the `sys::TypePath` or even `sys::Type` and not just `sys::Ident`.

My use-case is https://docs.rs/derive_bounded/latest/derive_bounded/ 

An extended example
``` rust
trait Trait {
    type A: Clone;
    type B: Clone;
    type C: Clone;
}

// Here I want to extract `T::A`, `T::B`, `T::C` 
#[derive(Clone)]
struct A<T: Trait> {
    a: T::A,
    b: T::B,
    c: T::C
}

#[derive(Clone)]
#[bounded_to(T::A, T::B, T::C)]
struct B<T: Trait> {
    f: A<T>,
}
```

I started looking at it and seems that I would need to replicate all the logic to save the `syn::TypePath`.

**Comment by TedDriggs** [comment]
Sorry for the delayed response on this. Having looked over the code again, I'm not sure how much value `darling` provides here over copy-pasting `darling`'s traversal logic and amending it to your needs.

`darling::usage` exists because `darling_core` needed it for internal use, and it then made sense to expose so that other crates could leverage the functionality. However, given that it already needed to take a flag for different "operating modes", I'm not sure that it's actually a great API design for the long-term, and I'm hesitant to build more functionality on top of it.

I suspect that `syn::Visit` would help a lot here.

**Comment by lu-zero** [comment]
I'll investigate it, thank you :)
