### ISSUE TITLE
Include supported shapes in unsupported shape error messages

### ISSUE THREAD

**Issue by Diwakar-Gupta** [TedDriggs/darling#222]
I cannot match the kind of error because it is `not public` to external crate.

https://github.com/TedDriggs/darling/blob/bafada6f97fd67dfba9005e47934f80b66ec7977/core/src/error/kind.rs#L12-L13

I wanted to give custom error message when `king = UnsupportedShape`.

**Comment by TedDriggs** [comment]
That’s by design - I don’t want to commit to having the internals of darling errors public. What are you trying to override the message to say? Maybe we could instead improve the message darling emits?

**Comment by TedDriggs** [comment]
Let's make the error message better - that way everyone who uses the crate will benefit, and you won't need to do any pattern matching on the error's contents in your project.

To do that, we'll need a new function on `Error` that takes both the observed unsupported shape and something that represents the allowed shapes. We'll change the `ErrorKind::UnsupportedShape` variant from a newtype variant to a named-fields variant, and store the `expected` value in an `Option` so we don't break compatibility for existing code. Then when we display the error, if that `Option` has a value, we'll add a sentence to the error message that says what shapes are accepted.

Does that meet SeaQL's needs?

**Comment by TedDriggs** [comment]
Looking at the code for this, I think the best path forward is something like...

1. Rework `darling_core::options::shape::DataShape` and expose the replacement under `darling_core::util`; this way we're able to use an actual method to do the validation instead of the current approach which relies entirely on generated code. This has the secondary benefit of enabling per-variant shape validation code [like this](https://github.com/TedDriggs/from_variants/blob/master/from_variants_impl/src/parser.rs#L67) to benefit from this work.
2. Rework `darling_core::options::Shape` to use the new `DataShape` in its generated validation code.

**Comment by Diwakar-Gupta** [comment]
> Let's make the error message better - that way everyone who uses the crate will benefit, and you won't need to do any pattern matching on the error's contents in your project.
> 
> To do that, we'll need a new function on `Error` that takes both the observed unsupported shape and something that represents the allowed shapes. We'll change the `ErrorKind::UnsupportedShape` variant from a newtype variant to a named-fields variant, and store the `expected` value in an `Option` so we don't break compatibility for existing code. Then when we display the error, if that `Option` has a value, we'll add a sentence to the error message that says what shapes are accepted.
> 
> Does that meet SeaQL's needs?

Yes, this will meet SeaQL's needs.
Thanks for the feature, this will help.
