### ISSUE TITLE
Should be `TokenStream2`

### ISSUE THREAD

**Issue by smoelius** [TedDriggs/darling#231]
Nit, but the documentation has this:
```rust
use proc_macro::TokenStream;
...
fn your_attr(args: TokenStream, input: TokenStream) -> TokenStream {
    let attr_args = match NestedMeta::parse_meta_list(args) {
```
For `args` to be valid for `parse_meta_list`, I think it should be a `proc_macro2::TokenStream`, not a `proc_macro::TokenStream`.

**Comment by TedDriggs** [comment]
Good catch, though I think your proposed fix isn't quite right. If this were a `proc_macro2::TokenStream` this wouldn't compile, because that function is the one you're exposing as a proc-macro out of your crate. The correct fix here would be to add the conversion of `args` to a `proc_macro2::TokenStream`.

**Comment by smoelius** [comment]
You're of course right. (Sorry for my poor explanation.)

**Comment by TedDriggs** [comment]
Want to submit a PR with the fix?

**Comment by smoelius** [comment]
👍 Sent.
