### ISSUE TITLE
Give access to a Flag Span

### ISSUE THREAD

**Issue by Ten0** [TedDriggs/darling#242]
Sometimes flags are incompatible with others and you'd like to refer to the span of one in the error.
For that purpose it would be useful to get the span at the same time.

```rust
impl Flag {
    /// If the flag is present, gives its span. If it's not present, `None`.
    pub fn present_span() -> Option<&Span> {
        self.0.as_ref()
    }
}
```

**Comment by TedDriggs** [comment]
We could expose an inherent method for this - previously, it was exposed via the `Spanned` trait but that was broken as part of the syn v2 update (see dtolnay/syn#1441)

**Comment by TedDriggs** [comment]
If we did this, I wouldn't have it borrow the span - I'd do:

```
impl Flag {
    pub fn span(&self) -> Span {
        self.0.copied().unwrap_or_else(Span::call_site)
    }
}
```

**Comment by greyblake** [comment]
I ran into the similar issue.
I'm trying to get a span out of `Flag` to generate a custom error message, but there is not way to get it.
The [doc for Flag](https://docs.rs/darling/latest/darling/util/struct.Flag.html#example) says use 

```rs
Err(Error::custom("Cannot set flag_a and flag_b").with_span(self.flag_b))
```

`.with_span` is based on `Spanned` trait from `syn`, but `Flag` does not implement it in the current version.

**Comment by Ten0** [comment]
Oh I wasn't aware `Span` had `Copy`. Yeah that seems to be a better interface.

**Comment by TedDriggs** [comment]
@greyblake without the linked `syn` issue being resolved, using `Flag` with the errors API is going to be painful, sadly. I suppose it would be possible to incur a breaking change by:

1. Introduce `darling_core::Spanned`
2. Add `impl <T: syn::spanned::Spanned> Spanned for T`
3. Update `with_span` to rely on the `darling_core` trait instead of the `syn` version
4. Add `impl darling_core::Spanned for Flag`

However, my preference would be that dtolnay/syn#1441 get fixed, so I can simply re-add the `Spanned` impl to `Flag` directly.

**Comment by greyblake** [comment]
@TedDriggs Thank you for the update!

To be honest I am a bit confused what word "sealed" means exactly in this context.
I see that the `Spanned` trait is available in syn 2: https://docs.rs/syn/latest/syn/spanned/trait.Spanned.html
And many other things based on it are still functioning.

For now I've switched to `bool` instead of `Flag` as a workaround to be able to get the proper span (tough I know, it's not exactly the same).
