### ISSUE TITLE
Parsing alternative syntax in derived impl of `FromMeta` for enum

### ISSUE THREAD

**Issue by ubolonton** [TedDriggs/darling#74]
I'm trying to use darling for an attr macro.

Currently, given these definitions:
```rust
#[derive(Debug, FromMeta)]
enum Name {
    Fn,          // Use function name.
    Crate,       // Use crate name.
    Str(String), // Explicitly specify a name.
}

#[derive(Debug, FromMeta)]
struct Package {
    name: Name,
}
```

It can parse the cases below:
```rust
#[pkg(name = "fn")]
#[pkg(name = "crate")]
#[pkg(name(str = "custom-name"))]
```

Is it possible to configure the derived impl of `FromMeta` to parse the following cases instead?
```rust
#[pkg(name(fn))]             // Fn(bool) works but then name(fn = false) is valid.
#[pkg(name(crate)]
#[pkg(name = "custom-name")] // Since there's only 1 variant with 1 String field.
#[pkg(name("custom-name")]   // Same with the above.
```

**Comment by TedDriggs** [comment]
You won't be able to do that with derived impls, but it should be possible to do it manually.

The way to do this would be to manually implement `from_list` and `from_str`. In `from_list`, you could `darling::util::IdentList` to grab all the words and then make sure there was only one, while in `from_str` you could immediately construct the desired variant.

For future reference, in the `#[pkg(name(fn))]` case, I think the type you want is [`darling::util::Flag`](https://docs.rs/darling/0.9.0/darling/util/struct.Flag.html), which allows the field to be optional but not false.

**Comment by ubolonton** [comment]
Yeah, I ended up implementing `from_list` and `from_string` manually.

I wish there was something like `#[darling(alt_variant)]` though.

**Comment by TedDriggs** [comment]
I have #63 open right now, but I haven't come up with a satisfactory way to represent the case you're describing yet.

**Comment by thedodd** [comment]
@TedDriggs one issue that I'm running into right now is that if a user attempts to specify a value for an enum attribute being derived, if the user does not use the correct syntax, it looks like the value is either:
- skipped and set to a default if `#[darling(default)]` is specified on the corresponding `FDI` field.
- or if no default attr is present, then a `Missing field` error is generated ... which is going to be deceptive to users because the field is there, it is just specified in a way that is apparently unexpected by darling.

To use the example which @ubolonton gave above for the type `enum Name`, if the end user were to attempt to provide the attribute as a type literal, say `#[pkg(name = Name::Fn)]` or `#[pkg(name = Name::Str("val"))]`, doing so would trigger the behavior I've described above.

The behavior I would expect would be that an error would be generated telling the user that they've specified the value for the attribute incorrectly. Any thoughts on what we should do to fix this issue? 

I'm happy to dive in a fix the code if it is an obvious issue. I've looked through the code a bit and see where the errors are being generated ... I just need to take a deeper dive into the process of building the `TraitImpl.data` and such.
